CREATE MULTISET TABLE Workspace.InternationalOrders 
(
  OrderID              INTEGER NOT NULL,
  CustomsDescription   VARCHAR(100) NOT NULL,
  ExciseTax            DECIMAL(19,4) NOT NULL
 )Primary Index(OrderID);
 
 Insert into Workspace.InternationalOrders Values  (10318, 'Lakkalikööri and other Workspace.Products for personal use', 109.8305);
Insert into Workspace.InternationalOrders Values  (10461, 'Sir Rodney''s Scones and other Workspace.Products for personal use', 937.3054);
Insert into Workspace.InternationalOrders Values  (10930, 'Sir Rodney''s Scones and other Workspace.Products for personal use', 1121.6050);
Insert into Workspace.InternationalOrders Values  (10522, 'Northwoods Cranberry Sauce and other Workspace.Products for personal use', 1214.2573);
Insert into Workspace.InternationalOrders Values  (10583, 'Thüringer Rostbratwurst and other Workspace.Products for personal use', 1102.8278);
Insert into Workspace.InternationalOrders Values  (10257, 'Schoggi Schokolade and other Workspace.Products for personal use', 511.6438);
Insert into Workspace.InternationalOrders Values  (10848, 'Mishi Kobe Niku and other Workspace.Products for personal use', 425.5703);
Insert into Workspace.InternationalOrders Values  (10379, 'Vegie-spread and other Workspace.Products for personal use', 438.2255);
Insert into Workspace.InternationalOrders Values  (10726, 'Queso Cabrales and other Workspace.Products for personal use', 299.2470);
Insert into Workspace.InternationalOrders Values  (10623, 'Tofu and other Workspace.Products for personal use', 653.2036);
Insert into Workspace.InternationalOrders Values  (10991, 'Outback Lager and other Workspace.Products for personal use', 1311.2042);
Insert into Workspace.InternationalOrders Values  (11052, 'Sirop d''érable and other Workspace.Products for personal use', 760.6812);
Insert into Workspace.InternationalOrders Values  (10909, 'Uncle Bob''s Organic Dried Pears and other Workspace.Products for personal use', 306.0999);
Insert into Workspace.InternationalOrders Values  (10501, 'Tourtière and other Workspace.Products for personal use', 68.0730);
Insert into Workspace.InternationalOrders Values  (10644, 'Spegesild and other Workspace.Products for personal use', 649.6629);
Insert into Workspace.InternationalOrders Values  (10724, 'Sirop d''érable and other Workspace.Products for personal use', 291.7087);
Insert into Workspace.InternationalOrders Values  (10888, 'Scottish Longbreads and other Workspace.Products for personal use', 276.4037);
Insert into Workspace.InternationalOrders Values  (10787, 'Thüringer Rostbratwurst and other Workspace.Products for personal use', 1261.3145);
Insert into Workspace.InternationalOrders Values  (10827, 'Ikura and other Workspace.Products for personal use', 385.1377);
Insert into Workspace.InternationalOrders Values  (10705, 'Mascarpone Fabioli and other Workspace.Products for personal use', 172.6952);
Insert into Workspace.InternationalOrders Values  (10297, 'Mozzarella di Giovanni and other Workspace.Products for personal use', 648.7491);
Insert into Workspace.InternationalOrders Values  (10970, 'Filo Mix and other Workspace.Products for personal use', 127.9224);
Insert into Workspace.InternationalOrders Values  (10438, 'Teatime Chocolate Biscuits and other Workspace.Products for personal use', 259.2712);
Insert into Workspace.InternationalOrders Values  (10480, 'Zaanse koeken and other Workspace.Products for personal use', 345.3904);
Insert into Workspace.InternationalOrders Values  (10562, 'Tarte au sucre and other Workspace.Products for personal use', 248.0780);
Insert into Workspace.InternationalOrders Values  (10663, 'Singaporean Hokkien Fried Mee and other Workspace.Products for personal use', 928.3509);
Insert into Workspace.InternationalOrders Values  (10745, 'Raclette Courdavault and other Workspace.Products for personal use', 2069.5097);
Insert into Workspace.InternationalOrders Values  (10766, 'Uncle Bob''s Organic Dried Pears and other Workspace.Products for personal use', 1055.3595);
Insert into Workspace.InternationalOrders Values  (10358, 'Sasquatch Ale and other Workspace.Products for personal use', 206.5032);
Insert into Workspace.InternationalOrders Values  (10764, 'Chartreuse verte and other Workspace.Products for personal use', 1160.4386);
Insert into Workspace.InternationalOrders Values  (10337, 'Tunnbröd and other Workspace.Products for personal use', 1127.0874);
Insert into Workspace.InternationalOrders Values  (10602, 'Original Frankfurter grüne Soße and other Workspace.Products for personal use', 29.6963);
Insert into Workspace.InternationalOrders Values  (10459, 'Uncle Bob''s Organic Dried Pears and other Workspace.Products for personal use', 771.1891);
Insert into Workspace.InternationalOrders Values  (11010, 'Uncle Bob''s Organic Dried Pears and other Workspace.Products for personal use', 294.6783);
Insert into Workspace.InternationalOrders Values  (10419, 'Gudbrandsdalsost and other Workspace.Products for personal use', 1008.7592);
Insert into Workspace.InternationalOrders Values  (10684, 'Zaanse koeken and other Workspace.Products for personal use', 807.7383);
Insert into Workspace.InternationalOrders Values  (11029, 'Vegie-spread and other Workspace.Products for personal use', 587.8946);
Insert into Workspace.InternationalOrders Values  (10377, 'Rössle Sauerkraut and other Workspace.Products for personal use', 464.1754);
Insert into Workspace.InternationalOrders Values  (11071, 'Uncle Bob''s Organic Dried Pears and other Workspace.Products for personal use', 233.0014);
Insert into Workspace.InternationalOrders Values  (10255, 'Raclette Courdavault and other Workspace.Products for personal use', 1137.8237);
Insert into Workspace.InternationalOrders Values  (10928, 'Zaanse koeken and other Workspace.Products for personal use', 62.8190);
Insert into Workspace.InternationalOrders Values  (10276, 'Konbu and other Workspace.Products for personal use', 191.8835);
Insert into Workspace.InternationalOrders Values  (10949, 'Tarte au sucre and other Workspace.Products for personal use', 2020.2596);
Insert into Workspace.InternationalOrders Values  (10621, 'Tunnbröd and other Workspace.Products for personal use', 346.5325);
Insert into Workspace.InternationalOrders Values  (10703, 'Röd Kaviar and other Workspace.Products for personal use', 1162.7229);
Insert into Workspace.InternationalOrders Values  (10499, 'Rössle Sauerkraut and other Workspace.Products for personal use', 645.0942);
Insert into Workspace.InternationalOrders Values  (10520, 'Perth Pasties and other Workspace.Products for personal use', 91.3731);
Insert into Workspace.InternationalOrders Values  (10907, 'Rhönbräu Klosterbier and other Workspace.Products for personal use', 49.5699);
Insert into Workspace.InternationalOrders Values  (10581, 'Rhönbräu Klosterbier and other Workspace.Products for personal use', 177.0354);
Insert into Workspace.InternationalOrders Values  (10541, 'Louisiana Fiery Hot Pepper Sauce and other Workspace.Products for personal use', 988.1089);
Insert into Workspace.InternationalOrders Values  (10457, 'Raclette Courdavault and other Workspace.Products for personal use', 723.6751);
Insert into Workspace.InternationalOrders Values  (10968, 'Wimmers gute Semmelknödel and other Workspace.Products for personal use', 643.2667);
Insert into Workspace.InternationalOrders Values  (10417, 'Spegesild and other Workspace.Products for personal use', 5154.9057);
Insert into Workspace.InternationalOrders Values  (10785, 'Rhönbräu Klosterbier and other Workspace.Products for personal use', 177.0354);
Insert into Workspace.InternationalOrders Values  (10560, 'Tarte au sucre and other Workspace.Products for personal use', 574.4171);
Insert into Workspace.InternationalOrders Values  (11050, 'Lakkalikööri and other Workspace.Products for personal use', 411.1790);
Insert into Workspace.InternationalOrders Values  (10806, 'Louisiana Fiery Hot Pepper Sauce and other Workspace.Products for personal use', 261.3728);
Insert into Workspace.InternationalOrders Values  (10436, 'Wimmers gute Semmelknödel and other Workspace.Products for personal use', 1010.0384);
Insert into Workspace.InternationalOrders Values  (10295, 'Gnocchi di nonna Alice and other Workspace.Products for personal use', 55.5549);
Insert into Workspace.InternationalOrders Values  (10478, 'Ikura and other Workspace.Products for personal use', 226.6053);
Insert into Workspace.InternationalOrders Values  (10682, 'Rhönbräu Klosterbier and other Workspace.Products for personal use', 171.5530);
Insert into Workspace.InternationalOrders Values  (10356, 'Pâté chinois and other Workspace.Products for personal use', 505.4761);
Insert into Workspace.InternationalOrders Values  (10642, 'Sirop d''érable and other Workspace.Products for personal use', 397.4731);
Insert into Workspace.InternationalOrders Values  (10989, 'Queso Cabrales and other Workspace.Products for personal use', 618.4132);
Insert into Workspace.InternationalOrders Values  (10293, 'Vegie-spread and other Workspace.Products for personal use', 387.7418);
Insert into Workspace.InternationalOrders Values  (11008, 'Sasquatch Ale and other Workspace.Products for personal use', 2240.2404);
Insert into Workspace.InternationalOrders Values  (10743, 'Spegesild and other Workspace.Products for personal use', 153.5068);
Insert into Workspace.InternationalOrders Values  (10947, 'Raclette Courdavault and other Workspace.Products for personal use', 100.5104);
Insert into Workspace.InternationalOrders Values  (10825, 'Perth Pasties and other Workspace.Products for personal use', 470.9188);
Insert into Workspace.InternationalOrders Values  (10274, 'Mozzarella di Giovanni and other Workspace.Products for personal use', 246.0678);
Insert into Workspace.InternationalOrders Values  (10846, 'Outback Lager and other Workspace.Products for personal use', 508.0345);
Insert into Workspace.InternationalOrders Values  (10476, 'Pâté chinois and other Workspace.Products for personal use', 83.3323);
Insert into Workspace.InternationalOrders Values  (10926, 'Teatime Chocolate Biscuits and other Workspace.Products for personal use', 235.0117);
Insert into Workspace.InternationalOrders Values  (10539, 'Sir Rodney''s Scones and other Workspace.Products for personal use', 162.4157);
Insert into Workspace.InternationalOrders Values  (11069, 'Chartreuse verte and other Workspace.Products for personal use', 164.4716);
Insert into Workspace.InternationalOrders Values  (10886, 'Original Frankfurter grüne Soße and other Workspace.Products for personal use', 1428.8471);
Insert into Workspace.InternationalOrders Values  (10335, 'Mascarpone Fabioli and other Workspace.Products for personal use', 1162.8143);
Insert into Workspace.InternationalOrders Values  (10396, 'Tunnbröd and other Workspace.Products for personal use', 869.7807);
Insert into Workspace.InternationalOrders Values  (10741, 'Chang and other Workspace.Products for personal use', 130.2067);
Insert into Workspace.InternationalOrders Values  (10354, 'Thüringer Rostbratwurst and other Workspace.Products for personal use', 259.8651);
Insert into Workspace.InternationalOrders Values  (10865, 'Côte de Blaye and other Workspace.Products for personal use', 7880.9312);
Insert into Workspace.InternationalOrders Values  (10537, 'Röd Kaviar and other Workspace.Products for personal use', 833.2314);
Insert into Workspace.InternationalOrders Values  (10253, 'Maxilaku and other Workspace.Products for personal use', 660.0794);
Insert into Workspace.InternationalOrders Values  (10804, 'Rössle Sauerkraut and other Workspace.Products for personal use', 1046.4049);
Insert into Workspace.InternationalOrders Values  (10661, 'Escargots de Bourgogne and other Workspace.Products for personal use', 321.2907);
Insert into Workspace.InternationalOrders Values  (10333, 'Tofu and other Workspace.Products for personal use', 435.8498);
Insert into Workspace.InternationalOrders Values  (10823, 'Ravioli Angelo and other Workspace.Products for personal use', 1419.7098);
Insert into Workspace.InternationalOrders Values  (10783, 'Gorgonzola Telino and other Workspace.Products for personal use', 659.0286);
Insert into Workspace.InternationalOrders Values  (10373, 'Flotemysost and other Workspace.Products for personal use', 780.3264);
Insert into Workspace.InternationalOrders Values  (10518, 'Gula Malacca and other Workspace.Products for personal use', 1896.0150);
Insert into Workspace.InternationalOrders Values  (10291, 'Manjimup Dried Apples and other Workspace.Products for personal use', 252.5553);
Insert into Workspace.InternationalOrders Values  (10987, 'Uncle Bob''s Organic Dried Pears and other Workspace.Products for personal use', 1266.4314);
Insert into Workspace.InternationalOrders Values  (10802, 'Tarte au sucre and other Workspace.Products for personal use', 1792.6263);
Insert into Workspace.InternationalOrders Values  (10863, 'Escargots de Bourgogne and other Workspace.Products for personal use', 237.1132);
Insert into Workspace.InternationalOrders Values  (11048, 'Scottish Longbreads and other Workspace.Products for personal use', 239.8544);
Insert into Workspace.InternationalOrders Values  (10434, 'Queso Cabrales and other Workspace.Products for personal use', 164.4716);
Insert into Workspace.InternationalOrders Values  (10497, 'Original Frankfurter grüne Soße and other Workspace.Products for personal use', 630.7486);
Insert into Workspace.InternationalOrders Values  (10760, 'Schoggi Schokolade and other Workspace.Products for personal use', 1509.4839);
Insert into Workspace.InternationalOrders Values  (10844, 'Gustaf''s Knäckebröd and other Workspace.Products for personal use', 335.7962);
Insert into Workspace.InternationalOrders Values  (11067, 'Jack''s New England Clam Chowder and other Workspace.Products for personal use', 39.6788);
Insert into Workspace.InternationalOrders Values  (10720, 'Steeleye Stout and other Workspace.Products for personal use', 251.2761);
Insert into Workspace.InternationalOrders Values  (10640, 'Outback Lager and other Workspace.Products for personal use', 431.7380);
Insert into Workspace.InternationalOrders Values  (10699, 'Zaanse koeken and other Workspace.Products for personal use', 52.0827);
Insert into Workspace.InternationalOrders Values  (10762, 'Zaanse koeken and other Workspace.Products for personal use', 1981.4260);
Insert into Workspace.InternationalOrders Values  (10556, 'Mozzarella di Giovanni and other Workspace.Products for personal use', 381.5741);
Insert into Workspace.InternationalOrders Values  (10701, 'Raclette Courdavault and other Workspace.Products for personal use', 1539.6370);
Insert into Workspace.InternationalOrders Values  (10781, 'Tourtière and other Workspace.Products for personal use', 517.3317);
Insert into Workspace.InternationalOrders Values  (10985, 'Pavlova and other Workspace.Products for personal use', 1027.1252);
Insert into Workspace.InternationalOrders Values  (10905, 'Chai and other Workspace.Products for personal use', 164.4716);
Insert into Workspace.InternationalOrders Values  (10964, 'Gudbrandsdalsost and other Workspace.Products for personal use', 937.7166);
Insert into Workspace.InternationalOrders Values  (11027, 'Tarte au sucre and other Workspace.Products for personal use', 534.6698);
Insert into Workspace.InternationalOrders Values  (11025, 'Konbu and other Workspace.Products for personal use', 137.0597);
Insert into Workspace.InternationalOrders Values  (10966, 'Tarte au sucre and other Workspace.Products for personal use', 573.6404);
Insert into Workspace.InternationalOrders Values  (10474, 'Tofu and other Workspace.Products for personal use', 570.6708);
Insert into Workspace.InternationalOrders Values  (10312, 'Rössle Sauerkraut and other Workspace.Products for personal use', 737.7465);
Insert into Workspace.InternationalOrders Values  (10455, 'Sirop d''érable and other Workspace.Products for personal use', 1226.2272);
Insert into Workspace.InternationalOrders Values  (10352, 'Tourtière and other Workspace.Products for personal use', 70.3573);
Insert into Workspace.InternationalOrders Values  (10619, 'Sir Rodney''s Scones and other Workspace.Products for personal use', 575.6506);
Insert into Workspace.InternationalOrders Values  (10922, 'Guaraná Fantástica and other Workspace.Products for personal use', 339.2227);
Insert into Workspace.InternationalOrders Values  (10558, 'Zaanse koeken and other Workspace.Products for personal use', 979.0173);
Insert into Workspace.InternationalOrders Values  (10331, 'Tourtière and other Workspace.Products for personal use', 40.4326);
Insert into Workspace.InternationalOrders Values  (10943, 'Spegesild and other Workspace.Products for personal use', 324.8314);
Insert into Workspace.InternationalOrders Values  (10251, 'Ravioli Angelo and other Workspace.Products for personal use', 306.4654);
Insert into Workspace.InternationalOrders Values  (10779, 'Tarte au sucre and other Workspace.Products for personal use', 609.9155);
Insert into Workspace.InternationalOrders Values  (10945, 'Konbu and other Workspace.Products for personal use', 111.9321);
Insert into Workspace.InternationalOrders Values  (10840, 'NuNuCa Nuß-Nougat-Creme and other Workspace.Products for personal use', 120.6125);
Insert into Workspace.InternationalOrders Values  (10659, 'Outback Lager and other Workspace.Products for personal use', 590.0876);
Insert into Workspace.InternationalOrders Values  (10800, 'Tourtière and other Workspace.Products for personal use', 745.6732);
Insert into Workspace.InternationalOrders Values  (10392, 'Gudbrandsdalsost and other Workspace.Products for personal use', 657.8864);
Insert into Workspace.InternationalOrders Values  (10516, 'Singaporean Hokkien Fried Mee and other Workspace.Products for personal use', 1194.4751);
Insert into Workspace.InternationalOrders Values  (11044, 'Tarte au sucre and other Workspace.Products for personal use', 270.2817);
Insert into Workspace.InternationalOrders Values  (10924, 'Rössle Sauerkraut and other Workspace.Products for personal use', 929.4930);
Insert into Workspace.InternationalOrders Values  (10493, 'Louisiana Hot Spiced Okra and other Workspace.Products for personal use', 308.8411);
Insert into Workspace.InternationalOrders Values  (10413, 'Tarte au sucre and other Workspace.Products for personal use', 970.0170);
Insert into Workspace.InternationalOrders Values  (11065, 'Tourtière and other Workspace.Products for personal use', 115.3860);
Insert into Workspace.InternationalOrders Values  (10249, 'Tofu and other Workspace.Products for personal use', 851.3233);
Insert into Workspace.InternationalOrders Values  (11046, 'Steeleye Stout and other Workspace.Products for personal use', 714.5378);
Insert into Workspace.InternationalOrders Values  (10901, 'Jack''s New England Clam Chowder and other Workspace.Products for personal use', 426.9409);
Insert into Workspace.InternationalOrders Values  (10842, 'Scottish Longbreads and other Workspace.Products for personal use', 445.4439);
Insert into Workspace.InternationalOrders Values  (11063, 'Sasquatch Ale and other Workspace.Products for personal use', 660.3992);
Insert into Workspace.InternationalOrders Values  (10739, 'Inlagd Sill and other Workspace.Products for personal use', 109.6477);
Insert into Workspace.InternationalOrders Values  (10453, 'Outback Lager and other Workspace.Products for personal use', 206.9601);
Insert into Workspace.InternationalOrders Values  (10575, 'Vegie-spread and other Workspace.Products for personal use', 981.0731);
Insert into Workspace.InternationalOrders Values  (10495, 'Tunnbröd and other Workspace.Products for personal use', 127.0086);
Insert into Workspace.InternationalOrders Values  (10697, 'Teatime Chocolate Biscuits and other Workspace.Products for personal use', 490.6279);
Insert into Workspace.InternationalOrders Values  (10638, 'Rogede sild and other Workspace.Products for personal use', 1242.6972);
Insert into Workspace.InternationalOrders Values  (10512, 'Zaanse koeken and other Workspace.Products for personal use', 282.3429);
Insert into Workspace.InternationalOrders Values  (11004, 'Lakkalikööri and other Workspace.Products for personal use', 134.9490);
Insert into Workspace.InternationalOrders Values  (10962, 'Uncle Bob''s Organic Dried Pears and other Workspace.Products for personal use', 1637.4062);
Insert into Workspace.InternationalOrders Values  (11023, 'Uncle Bob''s Organic Dried Pears and other Workspace.Products for personal use', 685.2984);
Insert into Workspace.InternationalOrders Values  (10758, 'Outback Lager and other Workspace.Products for personal use', 751.3611);
Insert into Workspace.InternationalOrders Values  (10289, 'Wimmers gute Semmelknödel and other Workspace.Products for personal use', 219.0214);
Insert into Workspace.InternationalOrders Values  (10903, 'Scottish Longbreads and other Workspace.Products for personal use', 425.8216);
Insert into Workspace.InternationalOrders Values  (10266, 'Queso Manchego La Pastora and other Workspace.Products for personal use', 166.6646);
Insert into Workspace.InternationalOrders Values  (10718, 'Tarte au sucre and other Workspace.Products for personal use', 1582.1255);
Insert into Workspace.InternationalOrders Values  (10819, 'Rhönbräu Klosterbier and other Workspace.Products for personal use', 217.9249);
Insert into Workspace.InternationalOrders Values  (10350, 'Valkoinen suklaa and other Workspace.Products for personal use', 325.9279);
Insert into Workspace.InternationalOrders Values  (10472, 'Manjimup Dried Apples and other Workspace.Products for personal use', 480.2571);
Insert into Workspace.InternationalOrders Values  (10554, 'Tunnbröd and other Workspace.Products for personal use', 831.2669);
Insert into Workspace.InternationalOrders Values  (10270, 'Ipoh Coffee and other Workspace.Products for personal use', 628.6470);
Insert into Workspace.InternationalOrders Values  (10918, 'Chai and other Workspace.Products for personal use', 881.7506);
Insert into Workspace.InternationalOrders Values  (10411, 'Raclette Courdavault and other Workspace.Products for personal use', 552.1221);
Insert into Workspace.InternationalOrders Values  (10777, 'Singaporean Hokkien Fried Mee and other Workspace.Products for personal use', 127.9224);
Insert into Workspace.InternationalOrders Values  (10615, 'Pâté chinois and other Workspace.Products for personal use', 54.8239);
Insert into Workspace.InternationalOrders Values  (10533, 'Röd Kaviar and other Workspace.Products for personal use', 1048.5979);
Insert into Workspace.InternationalOrders Values  (10390, 'Steeleye Stout and other Workspace.Products for personal use', 1039.4606);
Insert into Workspace.InternationalOrders Values  (10535, 'Ravioli Angelo and other Workspace.Products for personal use', 985.2306);
Insert into Workspace.InternationalOrders Values  (10571, 'Tofu and other Workspace.Products for personal use', 295.9347);
Insert into Workspace.InternationalOrders Values  (10268, 'Thüringer Rostbratwurst and other Workspace.Products for personal use', 503.1004);
Insert into Workspace.InternationalOrders Values  (10491, 'Original Frankfurter grüne Soße and other Workspace.Products for personal use', 139.4811);
Insert into Workspace.InternationalOrders Values  (10880, 'Tunnbröd and other Workspace.Products for personal use', 856.6230);
Insert into Workspace.InternationalOrders Values  (10798, 'Tarte au sucre and other Workspace.Products for personal use', 204.0362);
Insert into Workspace.InternationalOrders Values  (10451, 'Wimmers gute Semmelknödel and other Workspace.Products for personal use', 1954.1968);
Insert into Workspace.InternationalOrders Values  (10514, 'Sir Rodney''s Marmalade and other Workspace.Products for personal use', 3939.7575);
Insert into Workspace.InternationalOrders Values  (10958, 'Uncle Bob''s Organic Dried Pears and other Workspace.Products for personal use', 356.8120);
Insert into Workspace.InternationalOrders Values  (10716, 'Sirop d''érable and other Workspace.Products for personal use', 322.5471);
Insert into Workspace.InternationalOrders Values  (10348, 'Tunnbröd and other Workspace.Products for personal use', 180.9188);
Insert into Workspace.InternationalOrders Values  (10695, 'Queso Manchego La Pastora and other Workspace.Products for personal use', 293.3077);
Insert into Workspace.InternationalOrders Values  (10960, 'Jack''s New England Clam Chowder and other Workspace.Products for personal use', 126.3690);
Insert into Workspace.InternationalOrders Values  (10981, 'Côte de Blaye and other Workspace.Products for personal use', 7223.0448);
Insert into Workspace.InternationalOrders Values  (10371, 'Inlagd Sill and other Workspace.Products for personal use', 41.6661);
Insert into Workspace.InternationalOrders Values  (10754, 'Boston Crab Meat and other Workspace.Products for personal use', 25.2190);
Insert into Workspace.InternationalOrders Values  (10308, 'Outback Lager and other Workspace.Products for personal use', 40.5697);
Insert into Workspace.InternationalOrders Values  (10817, 'Tarte au sucre and other Workspace.Products for personal use', 5249.7053);
Insert into Workspace.InternationalOrders Values  (10409, 'Tofu and other Workspace.Products for personal use', 145.8315);
Insert into Workspace.InternationalOrders Values  (10857, 'Thüringer Rostbratwurst and other Workspace.Products for personal use', 1201.9905);
Insert into Workspace.InternationalOrders Values  (10634, 'Uncle Bob''s Organic Dried Pears and other Workspace.Products for personal use', 2277.7033);
Insert into Workspace.InternationalOrders Values  (10636, 'Escargots de Bourgogne and other Workspace.Products for personal use', 287.5969);
Insert into Workspace.InternationalOrders Values  (10550, 'Teatime Chocolate Biscuits and other Workspace.Products for personal use', 342.1923);
Insert into Workspace.InternationalOrders Values  (10573, 'Sasquatch Ale and other Workspace.Products for personal use', 951.1941);
Insert into Workspace.InternationalOrders Values  (10674, 'Tunnbröd and other Workspace.Products for personal use', 20.5590);
Insert into Workspace.InternationalOrders Values  (10878, 'Sir Rodney''s Marmalade and other Workspace.Products for personal use', 740.1222);
Insert into Workspace.InternationalOrders Values  (10632, 'Geitost and other Workspace.Products for personal use', 283.2567);
Insert into Workspace.InternationalOrders Values  (10531, 'Raclette Courdavault and other Workspace.Products for personal use', 50.2552);
Insert into Workspace.InternationalOrders Values  (10676, 'Teatime Chocolate Biscuits and other Workspace.Products for personal use', 244.3546);
Insert into Workspace.InternationalOrders Values  (10468, 'Nord-Ost Matjeshering and other Workspace.Products for personal use', 327.8467);
Insert into Workspace.InternationalOrders Values  (11042, 'Sirop d''érable and other Workspace.Products for personal use', 185.3732);
Insert into Workspace.InternationalOrders Values  (10939, 'Laughing Lumberjack Lager and other Workspace.Products for personal use', 342.6492);
Insert into Workspace.InternationalOrders Values  (10470, 'Wimmers gute Semmelknödel and other Workspace.Products for personal use', 831.8608);
Insert into Workspace.InternationalOrders Values  (10897, 'Thüringer Rostbratwurst and other Workspace.Products for personal use', 4950.2482);
Insert into Workspace.InternationalOrders Values  (10327, 'Queso Cabrales and other Workspace.Products for personal use', 1033.6584);
Insert into Workspace.InternationalOrders Values  (10737, 'Konbu and other Workspace.Products for personal use', 63.8698);
Insert into Workspace.InternationalOrders Values  (10916, 'Ravioli Angelo and other Workspace.Products for personal use', 313.7296);
Insert into Workspace.InternationalOrders Values  (10430, 'Sir Rodney''s Scones and other Workspace.Products for personal use', 2647.9929);
Insert into Workspace.InternationalOrders Values  (10979, 'Vegie-spread and other Workspace.Products for personal use', 2199.1225);
Insert into Workspace.InternationalOrders Values  (10592, 'Gumbär Gummibärchen and other Workspace.Products for personal use', 248.3750);
Insert into Workspace.InternationalOrders Values  (10937, 'Sasquatch Ale and other Workspace.Products for personal use', 294.5869);
Insert into Workspace.InternationalOrders Values  (10796, 'Wimmers gute Semmelknödel and other Workspace.Products for personal use', 1314.8957);
Insert into Workspace.InternationalOrders Values  (10859, 'Wimmers gute Semmelknödel and other Workspace.Products for personal use', 657.0869);
Insert into Workspace.InternationalOrders Values  (10712, 'Perth Pasties and other Workspace.Products for personal use', 565.7823);
Insert into Workspace.InternationalOrders Values  (11021, 'Sir Rodney''s Marmalade and other Workspace.Products for personal use', 3171.3279);
Insert into Workspace.InternationalOrders Values  (10836, 'Wimmers gute Semmelknödel and other Workspace.Products for personal use', 2149.7810);
Insert into Workspace.InternationalOrders Values  (10653, 'Pavlova and other Workspace.Products for personal use', 549.8377);
Insert into Workspace.InternationalOrders Values  (10977, 'Zaanse koeken and other Workspace.Products for personal use', 1020.1808);
Insert into Workspace.InternationalOrders Values  (10306, 'Tourtière and other Workspace.Products for personal use', 227.7475);
Insert into Workspace.InternationalOrders Values  (10655, 'Jack''s New England Clam Chowder and other Workspace.Products for personal use', 88.1751);
Insert into Workspace.InternationalOrders Values  (11038, 'Flotemysost and other Workspace.Products for personal use', 343.1061);
Insert into Workspace.InternationalOrders Values  (10613, 'Rhönbräu Klosterbier and other Workspace.Products for personal use', 163.5579);
Insert into Workspace.InternationalOrders Values  (10264, 'Jack''s New England Clam Chowder and other Workspace.Products for personal use', 330.9991);
Insert into Workspace.InternationalOrders Values  (10367, 'Tourtière and other Workspace.Products for personal use', 381.1173);
Insert into Workspace.InternationalOrders Values  (10283, 'Teatime Chocolate Biscuits and other Workspace.Products for personal use', 646.3734);
Insert into Workspace.InternationalOrders Values  (10611, 'Chang and other Workspace.Products for personal use', 369.1474);
Insert into Workspace.InternationalOrders Values  (10920, 'Valkoinen suklaa and other Workspace.Products for personal use', 178.1776);
Insert into Workspace.InternationalOrders Values  (10630, 'Pâté chinois and other Workspace.Products for personal use', 419.4026);
Insert into Workspace.InternationalOrders Values  (10449, 'Tarte au sucre and other Workspace.Products for personal use', 839.8103);
Insert into Workspace.InternationalOrders Values  (10529, 'Scottish Longbreads and other Workspace.Products for personal use', 432.1948);
Insert into Workspace.InternationalOrders Values  (10590, 'Original Frankfurter grüne Soße and other Workspace.Products for personal use', 520.8268);
Insert into Workspace.InternationalOrders Values  (10609, 'Sir Rodney''s Scones and other Workspace.Products for personal use', 193.7110);
Insert into Workspace.InternationalOrders Values  (10876, 'Wimmers gute Semmelknödel and other Workspace.Products for personal use', 418.9457);
Insert into Workspace.InternationalOrders Values  (10838, 'Inlagd Sill and other Workspace.Products for personal use', 1180.7691);
Insert into Workspace.InternationalOrders Values  (10691, 'Thüringer Rostbratwurst and other Workspace.Products for personal use', 4643.9472);
Insert into Workspace.InternationalOrders Values  (10428, 'Spegesild and other Workspace.Products for personal use', 87.7182);
Insert into Workspace.InternationalOrders Values  (10794, 'Tourtière and other Workspace.Products for personal use', 179.7538);
Insert into Workspace.InternationalOrders Values  (10447, 'Teatime Chocolate Biscuits and other Workspace.Products for personal use', 417.7579);
Insert into Workspace.InternationalOrders Values  (10527, 'Inlagd Sill and other Workspace.Products for personal use', 762.9655);
Insert into Workspace.InternationalOrders Values  (10998, 'Sirop d''érable and other Workspace.Products for personal use', 313.4098);
Insert into Workspace.InternationalOrders Values  (10899, 'Chartreuse verte and other Workspace.Products for personal use', 65.7886);
Insert into Workspace.InternationalOrders Values  (10384, 'Sir Rodney''s Marmalade and other Workspace.Products for personal use', 1015.3381);
Insert into Workspace.InternationalOrders Values  (10285, 'Perth Pasties and other Workspace.Products for personal use', 995.6015);
Insert into Workspace.InternationalOrders Values  (10508, 'Konbu and other Workspace.Products for personal use', 109.6477);
Insert into Workspace.InternationalOrders Values  (10895, 'Guaraná Fantástica and other Workspace.Products for personal use', 2914.5283);
Insert into Workspace.InternationalOrders Values  (10649, 'Rössle Sauerkraut and other Workspace.Products for personal use', 655.1452);
Insert into Workspace.InternationalOrders Values  (10426, 'Wimmers gute Semmelknödel and other Workspace.Products for personal use', 154.5119);
Insert into Workspace.InternationalOrders Values  (10287, 'Spegesild and other Workspace.Products for personal use', 422.1438);
Insert into Workspace.InternationalOrders Values  (10853, 'Carnarvon Tigers and other Workspace.Products for personal use', 285.5410);
Insert into Workspace.InternationalOrders Values  (10733, 'Tofu and other Workspace.Products for personal use', 666.5669);
Insert into Workspace.InternationalOrders Values  (10834, 'Thüringer Rostbratwurst and other Workspace.Products for personal use', 689.0081);
Insert into Workspace.InternationalOrders Values  (10487, 'Tourtière and other Workspace.Products for personal use', 422.6463);
Insert into Workspace.InternationalOrders Values  (10914, 'Flotemysost and other Workspace.Products for personal use', 245.5652);
Insert into Workspace.InternationalOrders Values  (10548, 'Sasquatch Ale and other Workspace.Products for personal use', 125.6837);
Insert into Workspace.InternationalOrders Values  (10552, 'Rhönbräu Klosterbier and other Workspace.Products for personal use', 402.2701);
Insert into Workspace.InternationalOrders Values  (10302, 'Rössle Sauerkraut and other Workspace.Products for personal use', 1237.5575);
Insert into Workspace.InternationalOrders Values  (10325, 'Tofu and other Workspace.Products for personal use', 683.9278);
Insert into Workspace.InternationalOrders Values  (10956, 'Zaanse koeken and other Workspace.Products for personal use', 309.2980);
Insert into Workspace.InternationalOrders Values  (10752, 'Gudbrandsdalsost and other Workspace.Products for personal use', 115.1301);
Insert into Workspace.InternationalOrders Values  (10975, 'Rhönbräu Klosterbier and other Workspace.Products for personal use', 327.8011);
Insert into Workspace.InternationalOrders Values  (10935, 'Tunnbröd and other Workspace.Products for personal use', 319.8059);
Insert into Workspace.InternationalOrders Values  (10388, 'Rogede sild and other Workspace.Products for personal use', 582.0467);
Insert into Workspace.InternationalOrders Values  (11036, 'Raclette Courdavault and other Workspace.Products for personal use', 773.0166);
Insert into Workspace.InternationalOrders Values  (11059, 'Konbu and other Workspace.Products for personal use', 839.7189);
Insert into Workspace.InternationalOrders Values  (10874, 'Ikura and other Workspace.Products for personal use', 141.6283);
Insert into Workspace.InternationalOrders Values  (10405, 'Aniseed Syrup and other Workspace.Products for personal use', 182.7462);
Insert into Workspace.InternationalOrders Values  (10912, 'Thüringer Rostbratwurst and other Workspace.Products for personal use', 3777.0905);
Insert into Workspace.InternationalOrders Values  (10771, 'Flotemysost and other Workspace.Products for personal use', 157.1618);
Insert into Workspace.InternationalOrders Values  (10489, 'Queso Cabrales and other Workspace.Products for personal use', 229.4379);
Insert into Workspace.InternationalOrders Values  (10628, 'Chai and other Workspace.Products for personal use', 205.5895);
Insert into Workspace.InternationalOrders Values  (10773, 'Rhönbräu Klosterbier and other Workspace.Products for personal use', 1012.5283);
Insert into Workspace.InternationalOrders Values  (10281, 'Teatime Chocolate Biscuits and other Workspace.Products for personal use', 39.5189);
Insert into Workspace.InternationalOrders Values  (10670, 'Tunnbröd and other Workspace.Products for personal use', 1051.5903);
Insert into Workspace.InternationalOrders Values  (10361, 'Chartreuse verte and other Workspace.Products for personal use', 1038.7296);
Insert into Workspace.InternationalOrders Values  (10567, 'Raclette Courdavault and other Workspace.Products for personal use', 1420.3951);
Insert into Workspace.InternationalOrders Values  (11019, 'Spegesild and other Workspace.Products for personal use', 34.7218);
Insert into Workspace.InternationalOrders Values  (10689, 'Chai and other Workspace.Products for personal use', 287.8253);
Insert into Workspace.InternationalOrders Values  (10466, 'Spegesild and other Workspace.Products for personal use', 98.6830);
Insert into Workspace.InternationalOrders Values  (10546, 'Uncle Bob''s Organic Dried Pears and other Workspace.Products for personal use', 1284.7060);
Insert into Workspace.InternationalOrders Values  (10996, 'Singaporean Hokkien Fried Mee and other Workspace.Products for personal use', 255.8447);
Insert into Workspace.InternationalOrders Values  (10626, 'Perth Pasties and other Workspace.Products for personal use', 686.9431);
Insert into Workspace.InternationalOrders Values  (10832, 'Wimmers gute Semmelknödel and other Workspace.Products for personal use', 259.9337);
Insert into Workspace.InternationalOrders Values  (10407, 'Queso Cabrales and other Workspace.Products for personal use', 545.4975);
Insert into Workspace.InternationalOrders Values  (11015, 'Original Frankfurter grüne Soße and other Workspace.Products for personal use', 284.3303);
Insert into Workspace.InternationalOrders Values  (10731, 'Sir Rodney''s Scones and other Workspace.Products for personal use', 909.1625);
Insert into Workspace.InternationalOrders Values  (10872, 'Wimmers gute Semmelknödel and other Workspace.Products for personal use', 989.9363);
Insert into Workspace.InternationalOrders Values  (10710, 'Zaanse koeken and other Workspace.Products for personal use', 42.7169);
Insert into Workspace.InternationalOrders Values  (10605, 'Raclette Courdavault and other Workspace.Products for personal use', 1976.4005);
Insert into Workspace.InternationalOrders Values  (10893, 'Thüringer Rostbratwurst and other Workspace.Products for personal use', 2513.7247);
Insert into Workspace.InternationalOrders Values  (10672, 'Flotemysost and other Workspace.Products for personal use', 1923.6325);
Insert into Workspace.InternationalOrders Values  (10525, 'Inlagd Sill and other Workspace.Products for personal use', 386.5083);
Insert into Workspace.InternationalOrders Values  (10323, 'NuNuCa Nuß-Nougat-Creme and other Workspace.Products for personal use', 75.1087);
Insert into Workspace.InternationalOrders Values  (10260, 'Tarte au sucre and other Workspace.Products for personal use', 797.7787);
Insert into Workspace.InternationalOrders Values  (10750, 'Tofu and other Workspace.Products for personal use', 854.9097);
Insert into Workspace.InternationalOrders Values  (10870, 'Steeleye Stout and other Workspace.Products for personal use', 73.0985);
Insert into Workspace.InternationalOrders Values  (10973, 'Rhönbräu Klosterbier and other Workspace.Products for personal use', 133.1992);
Insert into Workspace.InternationalOrders Values  (10386, 'Sasquatch Ale and other Workspace.Products for personal use', 75.8397);
Insert into Workspace.InternationalOrders Values  (10994, 'Raclette Courdavault and other Workspace.Products for personal use', 452.2969);
Insert into Workspace.InternationalOrders Values  (10792, 'Tourtière and other Workspace.Products for personal use', 182.6777);
Insert into Workspace.InternationalOrders Values  (10729, 'Valkoinen suklaa and other Workspace.Products for personal use', 845.2013);
Insert into Workspace.InternationalOrders Values  (10342, 'Pâté chinois and other Workspace.Products for personal use', 1051.1563);
Insert into Workspace.InternationalOrders Values  (10727, 'Raclette Courdavault and other Workspace.Products for personal use', 781.2401);
Insert into Workspace.InternationalOrders Values  (10952, 'Rössle Sauerkraut and other Workspace.Products for personal use', 224.4124);
Insert into Workspace.InternationalOrders Values  (10651, 'Teatime Chocolate Biscuits and other Workspace.Products for personal use', 242.3215);
Insert into Workspace.InternationalOrders Values  (10586, 'Filo Mix and other Workspace.Products for personal use', 12.7922);
Insert into Workspace.InternationalOrders Values  (10588, 'Singaporean Hokkien Fried Mee and other Workspace.Products for personal use', 1781.7758);
Insert into Workspace.InternationalOrders Values  (10851, 'Ravioli Angelo and other Workspace.Products for personal use', 1251.8117);
Insert into Workspace.InternationalOrders Values  (10464, 'Ipoh Coffee and other Workspace.Products for personal use', 844.2876);
Insert into Workspace.InternationalOrders Values  (10277, 'Tarte au sucre and other Workspace.Products for personal use', 548.6042);
Insert into Workspace.InternationalOrders Values  (10258, 'Mascarpone Fabioli and other Workspace.Products for personal use', 922.2289);
Insert into Workspace.InternationalOrders Values  (10304, 'Raclette Courdavault and other Workspace.Products for personal use', 436.0325);
Insert into Workspace.InternationalOrders Values  (10830, 'Scottish Longbreads and other Workspace.Products for personal use', 901.8527);
Insert into Workspace.InternationalOrders Values  (11057, 'Outback Lager and other Workspace.Products for personal use', 20.5590);
Insert into Workspace.InternationalOrders Values  (10443, 'Rössle Sauerkraut and other Workspace.Products for personal use', 245.610);
Insert into Workspace.InternationalOrders Values  (10790, 'Uncle Bob''s Organic Dried Pears and other Workspace.Products for personal use', 388.3357);
Insert into Workspace.InternationalOrders Values  (10868, 'Steeleye Stout and other Workspace.Products for personal use', 915.8327);
Insert into Workspace.InternationalOrders Values  (10788, 'Teatime Chocolate Biscuits and other Workspace.Products for personal use', 351.7865);
Insert into Workspace.InternationalOrders Values  (10365, 'Queso Cabrales and other Workspace.Products for personal use', 184.2082);
Insert into Workspace.InternationalOrders Values  (10687, 'Thüringer Rostbratwurst and other Workspace.Products for personal use', 2833.4346);
Insert into Workspace.InternationalOrders Values  (10445, 'Tourtière and other Workspace.Products for personal use', 79.9058);
Insert into Workspace.InternationalOrders Values  (10891, 'Nord-Ost Matjeshering and other Workspace.Products for personal use', 177.4237);
Insert into Workspace.InternationalOrders Values  (11055, 'Ravioli Angelo and other Workspace.Products for personal use', 789.2353);
Insert into Workspace.InternationalOrders Values  (10664, 'Louisiana Fiery Hot Pepper Sauce and other Workspace.Products for personal use', 692.4940);
Insert into Workspace.InternationalOrders Values  (10380, 'Perth Pasties and other Workspace.Products for personal use', 648.6578);
Insert into Workspace.InternationalOrders Values  (11017, 'Raclette Courdavault and other Workspace.Products for personal use', 3083.8427);
Insert into Workspace.InternationalOrders Values  (10809, 'Filo Mix and other Workspace.Products for personal use', 63.9612);
Insert into Workspace.InternationalOrders Values  (10485, 'Pâté chinois and other Workspace.Products for personal use', 804.0834);
Insert into Workspace.InternationalOrders Values  (10279, 'Alice Mutton and other Workspace.Products for personal use', 213.8131);
Insert into Workspace.InternationalOrders Values  (10647, 'Teatime Chocolate Biscuits and other Workspace.Products for personal use', 290.5665);
Insert into Workspace.InternationalOrders Values  (10929, 'Sir Rodney''s Scones and other Workspace.Products for personal use', 536.7028);
Insert into Workspace.InternationalOrders Values  (10849, 'Gumbär Gummibärchen and other Workspace.Products for personal use', 480.6866);
Insert into Workspace.InternationalOrders Values  (10813, 'Spegesild and other Workspace.Products for personal use', 296.0489);
Insert into Workspace.InternationalOrders Values  (10666, 'Thüringer Rostbratwurst and other Workspace.Products for personal use', 2132.1642);
Insert into Workspace.InternationalOrders Values  (10954, 'Rogede sild and other Workspace.Products for personal use', 869.0040);
Insert into Workspace.InternationalOrders Values  (10910, 'Teatime Chocolate Biscuits and other Workspace.Products for personal use', 206.9144);
Insert into Workspace.InternationalOrders Values  (10422, 'Gumbär Gummibärchen and other Workspace.Products for personal use', 22.7519);
Insert into Workspace.InternationalOrders Values  (10439, 'Wimmers gute Semmelknödel and other Workspace.Products for personal use', 492.5011);
Insert into Workspace.InternationalOrders Values  (10645, 'Inlagd Sill and other Workspace.Products for personal use', 701.2887);
Insert into Workspace.InternationalOrders Values  (10506, 'Outback Lager and other Workspace.Products for personal use', 211.0719);
Insert into Workspace.InternationalOrders Values  (10523, 'Sir Rodney''s Marmalade and other Workspace.Products for personal use', 1240.8012);
Insert into Workspace.InternationalOrders Values  (10811, 'Tunnbröd and other Workspace.Products for personal use', 389.2495);
Insert into Workspace.InternationalOrders Values  (10298, 'Tarte au sucre and other Workspace.Products for personal use', 1428.6187);
Insert into Workspace.InternationalOrders Values  (11013, 'Tunnbröd and other Workspace.Products for personal use', 164.9285);
Insert into Workspace.InternationalOrders Values  (10908, 'Uncle Bob''s Organic Dried Pears and other Workspace.Products for personal use', 318.8922);
Insert into Workspace.InternationalOrders Values  (11072, 'Wimmers gute Semmelknödel and other Workspace.Products for personal use', 2383.9246);
Insert into Workspace.InternationalOrders Values  (10363, 'Rhönbräu Klosterbier and other Workspace.Products for personal use', 204.3103);
Insert into Workspace.InternationalOrders Values  (10584, 'Gorgonzola Telino and other Workspace.Products for personal use', 285.5410);
Insert into Workspace.InternationalOrders Values  (11076, 'Tofu and other Workspace.Products for personal use', 482.9069);
Insert into Workspace.InternationalOrders Values  (10563, 'Inlagd Sill and other Workspace.Products for personal use', 440.8753);
Insert into Workspace.InternationalOrders Values  (10462, 'Tunnbröd and other Workspace.Products for personal use', 71.2710);
Insert into Workspace.InternationalOrders Values  (10704, 'Guaraná Fantástica and other Workspace.Products for personal use', 272.0635);
Insert into Workspace.InternationalOrders Values  (10460, 'Scottish Longbreads and other Workspace.Products for personal use', 107.2720);
Insert into Workspace.InternationalOrders Values  (10424, 'Steeleye Stout and other Workspace.Products for personal use', 5250.8475);
Insert into Workspace.InternationalOrders Values  (10971, 'Thüringer Rostbratwurst and other Workspace.Products for personal use', 791.7755);
Insert into Workspace.InternationalOrders Values  (10769, 'Tarte au sucre and other Workspace.Products for personal use', 778.4989);
Insert into Workspace.InternationalOrders Values  (10746, 'Tarte au sucre and other Workspace.Products for personal use', 1056.1362);
Insert into Workspace.InternationalOrders Values  (10319, 'Rössle Sauerkraut and other Workspace.Products for personal use', 544.2183);
Insert into Workspace.InternationalOrders Values  (10744, 'Boston Crab Meat and other Workspace.Products for personal use', 420.3163);
Insert into Workspace.InternationalOrders Values  (10969, 'Spegesild and other Workspace.Products for personal use', 49.3415);
Insert into Workspace.InternationalOrders Values  (10403, 'Pavlova and other Workspace.Products for personal use', 459.5611);
Insert into Workspace.InternationalOrders Values  (10420, 'Röd Kaviar and other Workspace.Products for personal use', 866.9481);
Insert into Workspace.InternationalOrders Values  (10340, 'Jack''s New England Clam Chowder and other Workspace.Products for personal use', 1171.5861);
Insert into Workspace.InternationalOrders Values  (11011, 'Flotemysost and other Workspace.Products for personal use', 438.5910);
Insert into Workspace.InternationalOrders Values  (10502, 'Rogede sild and other Workspace.Products for personal use', 372.9394);
Insert into Workspace.InternationalOrders Values  (10336, 'Chef Anton''s Cajun Seasoning and other Workspace.Products for personal use', 144.7350);
Insert into Workspace.InternationalOrders Values  (10275, 'Raclette Courdavault and other Workspace.Products for personal use', 140.3491);
Insert into Workspace.InternationalOrders Values  (10668, 'Wimmers gute Semmelknödel and other Workspace.Products for personal use', 317.4074);
Insert into Workspace.InternationalOrders Values  (10685, 'Zaanse koeken and other Workspace.Products for personal use', 365.9950);
Insert into Workspace.InternationalOrders Values  (11074, 'Pavlova and other Workspace.Products for personal use', 111.6123);
Insert into Workspace.InternationalOrders Values  (10256, 'Perth Pasties and other Workspace.Products for personal use', 236.5650);
Insert into Workspace.InternationalOrders Values  (10767, 'Singaporean Hokkien Fried Mee and other Workspace.Products for personal use', 12.7922);
Insert into Workspace.InternationalOrders Values  (10580, 'Tofu and other Workspace.Products for personal use', 487.5213);
Insert into Workspace.InternationalOrders Values  (10540, 'Scottish Longbreads and other Workspace.Products for personal use', 4656.2369);
Insert into Workspace.InternationalOrders Values  (10933, 'Sirop d''érable and other Workspace.Products for personal use', 420.5905);
Insert into Workspace.InternationalOrders Values  (10725, 'Pâté chinois and other Workspace.Products for personal use', 131.4859);
Insert into Workspace.InternationalOrders Values  (10931, 'Ravioli Angelo and other Workspace.Products for personal use', 382.3965);
Insert into Workspace.InternationalOrders Values  (10561, 'Manjimup Dried Apples and other Workspace.Products for personal use', 1299.5541);
Insert into Workspace.InternationalOrders Values  (10359, 'Pavlova and other Workspace.Products for personal use', 1669.5696);
Insert into Workspace.InternationalOrders Values  (10376, 'Gorgonzola Telino and other Workspace.Products for personal use', 191.8835);
Insert into Workspace.InternationalOrders Values  (10397, 'Sir Rodney''s Scones and other Workspace.Products for personal use', 385.2291);
Insert into Workspace.InternationalOrders Values  (10321, 'Steeleye Stout and other Workspace.Products for personal use', 65.7886);
Insert into Workspace.InternationalOrders Values  (11051, 'Guaraná Fantástica and other Workspace.Products for personal use', 20.5590);
Insert into Workspace.InternationalOrders Values  (10828, 'Sir Rodney''s Marmalade and other Workspace.Products for personal use', 425.7987);
Insert into Workspace.InternationalOrders Values  (10418, 'Zaanse koeken and other Workspace.Products for personal use', 829.1197);
Insert into Workspace.InternationalOrders Values  (10542, 'Tourtière and other Workspace.Products for personal use', 225.6002);
Insert into Workspace.InternationalOrders Values  (10641, 'Chang and other Workspace.Products for personal use', 938.4019);
Insert into Workspace.InternationalOrders Values  (10559, 'Pâté chinois and other Workspace.Products for personal use', 250.2710);
Insert into Workspace.InternationalOrders Values  (10382, 'Thüringer Rostbratwurst and other Workspace.Products for personal use', 1324.9102);
Insert into Workspace.InternationalOrders Values  (10378, 'Flotemysost and other Workspace.Products for personal use', 47.1485);
Insert into Workspace.InternationalOrders Values  (10521, 'Steeleye Stout and other Workspace.Products for personal use', 103.0232);
Insert into Workspace.InternationalOrders Values  (10601, 'Raclette Courdavault and other Workspace.Products for personal use', 1043.9378);
Insert into Workspace.InternationalOrders Values  (10807, 'Boston Crab Meat and other Workspace.Products for personal use', 8.4063);
Insert into Workspace.InternationalOrders Values  (10620, 'Guaraná Fantástica and other Workspace.Products for personal use', 26.2698);
Insert into Workspace.InternationalOrders Values  (10355, 'Ravioli Angelo and other Workspace.Products for personal use', 219.2955);
Insert into Workspace.InternationalOrders Values  (10300, 'Scottish Longbreads and other Workspace.Products for personal use', 277.7743);
Insert into Workspace.InternationalOrders Values  (10296, 'Queso Cabrales and other Workspace.Products for personal use', 479.9830);
Insert into Workspace.InternationalOrders Values  (10786, 'Rhönbräu Klosterbier and other Workspace.Products for personal use', 874.3722);
Insert into Workspace.InternationalOrders Values  (10866, 'Nord-Ost Matjeshering and other Workspace.Products for personal use', 667.7547);
Insert into Workspace.InternationalOrders Values  (10990, 'Sirop d''érable and other Workspace.Products for personal use', 2252.8042);
Insert into Workspace.InternationalOrders Values  (10416, 'Teatime Chocolate Biscuits and other Workspace.Products for personal use', 328.9432);
Insert into Workspace.InternationalOrders Values  (10824, 'Outback Lager and other Workspace.Products for personal use', 114.5819);
Insert into Workspace.InternationalOrders Values  (10565, 'Wimmers gute Semmelknödel and other Workspace.Products for personal use', 324.8314);
Insert into Workspace.InternationalOrders Values  (10458, 'Rössle Sauerkraut and other Workspace.Products for personal use', 1777.6640);
Insert into Workspace.InternationalOrders Values  (10500, 'Rössle Sauerkraut and other Workspace.Products for personal use', 251.6416);
Insert into Workspace.InternationalOrders Values  (10315, 'Sasquatch Ale and other Workspace.Products for personal use', 236.1081);
Insert into Workspace.InternationalOrders Values  (10765, 'Louisiana Fiery Hot Pepper Sauce and other Workspace.Products for personal use', 769.3616);
Insert into Workspace.InternationalOrders Values  (10885, 'Outback Lager and other Workspace.Products for personal use', 552.3505);
Insert into Workspace.InternationalOrders Values  (10477, 'Sir Rodney''s Scones and other Workspace.Products for personal use', 307.0137);
Insert into Workspace.InternationalOrders Values  (11053, 'Wimmers gute Semmelknödel and other Workspace.Products for personal use', 1671.5569);
Insert into Workspace.InternationalOrders Values  (10927, 'Sir Rodney''s Marmalade and other Workspace.Products for personal use', 365.4925);
Insert into Workspace.InternationalOrders Values  (10826, 'Ravioli Angelo and other Workspace.Products for personal use', 333.5119);
Insert into Workspace.InternationalOrders Values  (10906, 'Sirop d''érable and other Workspace.Products for personal use', 195.3100);
Insert into Workspace.InternationalOrders Values  (10357, 'Ikura and other Workspace.Products for personal use', 621.3372);
Insert into Workspace.InternationalOrders Values  (11007, 'Thüringer Rostbratwurst and other Workspace.Products for personal use', 1203.3383);
Insert into Workspace.InternationalOrders Values  (10946, 'Original Frankfurter grüne Soße and other Workspace.Products for personal use', 643.0383);
Insert into Workspace.InternationalOrders Values  (10481, 'Maxilaku and other Workspace.Products for personal use', 672.5061);
Insert into Workspace.InternationalOrders Values  (10519, 'Ikura and other Workspace.Products for personal use', 1076.3753);
Insert into Workspace.InternationalOrders Values  (10683, 'Filo Mix and other Workspace.Products for personal use', 28.7825);
Insert into Workspace.InternationalOrders Values  (10334, 'Scottish Longbreads and other Workspace.Products for personal use', 66.1541);
Insert into Workspace.InternationalOrders Values  (10254, 'Pâté chinois and other Workspace.Products for personal use', 285.6324);
Insert into Workspace.InternationalOrders Values  (10456, 'Sir Rodney''s Scones and other Workspace.Products for personal use', 299.7038);
Insert into Workspace.InternationalOrders Values  (10742, 'Mozzarella di Giovanni and other Workspace.Products for personal use', 1424.5069);
Insert into Workspace.InternationalOrders Values  (10950, 'Chef Anton''s Cajun Seasoning and other Workspace.Products for personal use', 50.2552);
Insert into Workspace.InternationalOrders Values  (10599, 'Tarte au sucre and other Workspace.Products for personal use', 225.2347);
Insert into Workspace.InternationalOrders Values  (10948, 'Valkoinen suklaa and other Workspace.Products for personal use', 1079.2307);
Insert into Workspace.InternationalOrders Values  (10313, 'Inlagd Sill and other Workspace.Products for personal use', 83.3323);
Insert into Workspace.InternationalOrders Values  (10845, 'Wimmers gute Semmelknödel and other Workspace.Products for personal use', 1854.4174);
Insert into Workspace.InternationalOrders Values  (10925, 'Inlagd Sill and other Workspace.Products for personal use', 255.3879);
Insert into Workspace.InternationalOrders Values  (10557, 'Wimmers gute Semmelknödel and other Workspace.Products for personal use', 526.5376);
Insert into Workspace.InternationalOrders Values  (10399, 'Scottish Longbreads and other Workspace.Products for personal use', 806.6419);
Insert into Workspace.InternationalOrders Values  (10252, 'Sir Rodney''s Marmalade and other Workspace.Products for personal use', 1704.1086);
Insert into Workspace.InternationalOrders Values  (10273, 'Lakkalikööri and other Workspace.Products for personal use', 978.7888);
Insert into Workspace.InternationalOrders Values  (10435, 'Mozzarella di Giovanni and other Workspace.Products for personal use', 288.5563);
Insert into Workspace.InternationalOrders Values  (10437, 'Perth Pasties and other Workspace.Products for personal use', 179.5482);
Insert into Workspace.InternationalOrders Values  (10782, 'Gorgonzola Telino and other Workspace.Products for personal use', 5.7108);
Insert into Workspace.InternationalOrders Values  (11026, 'Manjimup Dried Apples and other Workspace.Products for personal use', 470.5715);
Insert into Workspace.InternationalOrders Values  (10582, 'Ravioli Angelo and other Workspace.Products for personal use', 150.7656);
Insert into Workspace.InternationalOrders Values  (10292, 'Sir Rodney''s Marmalade and other Workspace.Products for personal use', 592.0978);
Insert into Workspace.InternationalOrders Values  (10538, 'Outback Lager and other Workspace.Products for personal use', 63.8698);
Insert into Workspace.InternationalOrders Values  (10353, 'Queso Cabrales and other Workspace.Products for personal use', 4907.4673);
Insert into Workspace.InternationalOrders Values  (11068, 'Rössle Sauerkraut and other Workspace.Products for personal use', 1089.5330);
Insert into Workspace.InternationalOrders Values  (11047, 'Chef Anton''s Gumbo Mix and other Workspace.Products for personal use', 498.2119);
Insert into Workspace.InternationalOrders Values  (10414, 'Teatime Chocolate Biscuits and other Workspace.Products for personal use', 105.7187);
Insert into Workspace.InternationalOrders Values  (10643, 'Spegesild and other Workspace.Products for personal use', 496.1560);
Insert into Workspace.InternationalOrders Values  (10637, 'Valkoinen suklaa and other Workspace.Products for personal use', 1323.1969);
Insert into Workspace.InternationalOrders Values  (10803, 'Teatime Chocolate Biscuits and other Workspace.Products for personal use', 573.7318);
Insert into Workspace.InternationalOrders Values  (10618, 'Scottish Longbreads and other Workspace.Products for personal use', 1232.3949);
Insert into Workspace.InternationalOrders Values  (10517, 'Raclette Courdavault and other Workspace.Products for personal use', 160.8167);
Insert into Workspace.InternationalOrders Values  (10332, 'Zaanse koeken and other Workspace.Products for personal use', 1020.4550);
Insert into Workspace.InternationalOrders Values  (10679, 'Raclette Courdavault and other Workspace.Products for personal use', 301.5313);
Insert into Workspace.InternationalOrders Values  (10622, 'Scottish Longbreads and other Workspace.Products for personal use', 276.4037);
Insert into Workspace.InternationalOrders Values  (10433, 'Gnocchi di nonna Alice and other Workspace.Products for personal use', 388.8840);
Insert into Workspace.InternationalOrders Values  (10864, 'Steeleye Stout and other Workspace.Products for personal use', 128.8361);
Insert into Workspace.InternationalOrders Values  (10944, 'Queso Cabrales and other Workspace.Products for personal use', 520.4156);
Insert into Workspace.InternationalOrders Values  (10374, 'Gorgonzola Telino and other Workspace.Products for personal use', 209.7013);
Insert into Workspace.InternationalOrders Values  (10597, 'Ravioli Angelo and other Workspace.Products for personal use', 365.5382);
Insert into Workspace.InternationalOrders Values  (10250, 'Manjimup Dried Apples and other Workspace.Products for personal use', 828.2973);
Insert into Workspace.InternationalOrders Values  (10887, 'NuNuCa Nuß-Nougat-Creme and other Workspace.Products for personal use', 31.9806);
Insert into Workspace.InternationalOrders Values  (10902, 'Tarte au sucre and other Workspace.Products for personal use', 464.0841);
Insert into Workspace.InternationalOrders Values  (10721, 'Gula Malacca and other Workspace.Products for personal use', 444.3018);
Insert into Workspace.InternationalOrders Values  (10658, 'Sir Rodney''s Scones and other Workspace.Products for personal use', 2132.6485);
Insert into Workspace.InternationalOrders Values  (10475, 'Louisiana Hot Spiced Okra and other Workspace.Products for personal use', 809.0176);
Insert into Workspace.InternationalOrders Values  (10454, 'Spegesild and other Workspace.Products for personal use', 189.1423);
Insert into Workspace.InternationalOrders Values  (10311, 'Singaporean Hokkien Fried Mee and other Workspace.Products for personal use', 122.8055);
Insert into Workspace.InternationalOrders Values  (11009, 'Inlagd Sill and other Workspace.Products for personal use', 320.7196);
Insert into Workspace.InternationalOrders Values  (10799, 'Raclette Courdavault and other Workspace.Products for personal use', 724.1319);
Insert into Workspace.InternationalOrders Values  (10986, 'Sir Rodney''s Marmalade and other Workspace.Products for personal use', 1014.2416);
Insert into Workspace.InternationalOrders Values  (10351, 'Louisiana Fiery Hot Pepper Sauce and other Workspace.Products for personal use', 2593.9000);
Insert into Workspace.InternationalOrders Values  (11005, 'Raclette Courdavault and other Workspace.Products for personal use', 267.7232);
Insert into Workspace.InternationalOrders Values  (10923, 'Singaporean Hokkien Fried Mee and other Workspace.Products for personal use', 427.6262);
Insert into Workspace.InternationalOrders Values  (10576, 'Gula Malacca and other Workspace.Products for personal use', 383.0589);
Insert into Workspace.InternationalOrders Values  (11070, 'Pavlova and other Workspace.Products for personal use', 855.9377);
Insert into Workspace.InternationalOrders Values  (10717, 'Tourtière and other Workspace.Products for personal use', 608.4307);
Insert into Workspace.InternationalOrders Values  (10578, 'Steeleye Stout and other Workspace.Products for personal use', 217.9249);
Insert into Workspace.InternationalOrders Values  (10473, 'Geitost and other Workspace.Products for personal use', 105.2618);
Insert into Workspace.InternationalOrders Values  (10862, 'Queso Cabrales and other Workspace.Products for personal use', 265.4389);
Insert into Workspace.InternationalOrders Values  (11024, 'Louisiana Fiery Hot Pepper Sauce and other Workspace.Products for personal use', 898.5678);
Insert into Workspace.InternationalOrders Values  (10372, 'Sir Rodney''s Marmalade and other Workspace.Products for personal use', 5610.8576);
Insert into Workspace.InternationalOrders Values  (10784, 'Mozzarella di Giovanni and other Workspace.Products for personal use', 753.8282);
Insert into Workspace.InternationalOrders Values  (10370, 'Wimmers gute Semmelknödel and other Workspace.Products for personal use', 536.3602);
Insert into Workspace.InternationalOrders Values  (10843, 'Manjimup Dried Apples and other Workspace.Products for personal use', 96.8555);
Insert into Workspace.InternationalOrders Values  (10942, 'Maxilaku and other Workspace.Products for personal use', 255.8447);
Insert into Workspace.InternationalOrders Values  (10534, 'Tourtière and other Workspace.Products for personal use', 236.3823);
Insert into Workspace.InternationalOrders Values  (10391, 'Konbu and other Workspace.Products for personal use', 39.4732);
Insert into Workspace.InternationalOrders Values  (10841, 'Raclette Courdavault and other Workspace.Products for personal use', 2092.9012);
Insert into Workspace.InternationalOrders Values  (11049, 'Queso Manchego La Pastora and other Workspace.Products for personal use', 156.2480);
Insert into Workspace.InternationalOrders Values  (10471, 'Uncle Bob''s Organic Dried Pears and other Workspace.Products for personal use', 606.7175);
Insert into Workspace.InternationalOrders Values  (10536, 'Queso Manchego La Pastora and other Workspace.Products for personal use', 952.5647);
Insert into Workspace.InternationalOrders Values  (10330, 'Mozzarella di Giovanni and other Workspace.Products for personal use', 886.3192);
Insert into Workspace.InternationalOrders Values  (10860, 'Manjimup Dried Apples and other Workspace.Products for personal use', 237.1132);
Insert into Workspace.InternationalOrders Values  (10635, 'Gustaf''s Knäckebröd and other Workspace.Products for personal use', 630.5887);
Insert into Workspace.InternationalOrders Values  (10494, 'Gnocchi di nonna Alice and other Workspace.Products for personal use', 416.6614);
Insert into Workspace.InternationalOrders Values  (10702, 'Lakkalikööri and other Workspace.Products for personal use', 150.7656);
Insert into Workspace.InternationalOrders Values  (10940, 'Uncle Bob''s Organic Dried Pears and other Workspace.Products for personal use', 164.4716);
Insert into Workspace.InternationalOrders Values  (10698, 'Thüringer Rostbratwurst and other Workspace.Products for personal use', 1645.0496);
Insert into Workspace.InternationalOrders Values  (10961, 'Lakkalikööri and other Workspace.Products for personal use', 512.6032);
Insert into Workspace.InternationalOrders Values  (10982, 'Uncle Bob''s Organic Dried Pears and other Workspace.Products for personal use', 463.2617);
Insert into Workspace.InternationalOrders Values  (11022, 'Teatime Chocolate Biscuits and other Workspace.Products for personal use', 640.5255);
Insert into Workspace.InternationalOrders Values  (10759, 'Mascarpone Fabioli and other Workspace.Products for personal use', 146.1970);
Insert into Workspace.InternationalOrders Values  (10498, 'Singaporean Hokkien Fried Mee and other Workspace.Products for personal use', 262.6977);
Insert into Workspace.InternationalOrders Values  (10389, 'Tarte au sucre and other Workspace.Products for personal use', 837.3432);
Insert into Workspace.InternationalOrders Values  (10290, 'Thüringer Rostbratwurst and other Workspace.Products for personal use', 990.9414);
Insert into Workspace.InternationalOrders Values  (10654, 'Tourtière and other Workspace.Products for personal use', 305.5060);
Insert into Workspace.InternationalOrders Values  (10900, 'Outback Lager and other Workspace.Products for personal use', 20.5590);
Insert into Workspace.InternationalOrders Values  (10675, 'Tofu and other Workspace.Products for personal use', 650.1197);
Insert into Workspace.InternationalOrders Values  (10921, 'Vegie-spread and other Workspace.Products for personal use', 884.4918);
Insert into Workspace.InternationalOrders Values  (10967, 'Teatime Chocolate Biscuits and other Workspace.Products for personal use', 415.9304);
Insert into Workspace.InternationalOrders Values  (10858, 'Uncle Bob''s Organic Dried Pears and other Workspace.Products for personal use', 296.5058);
Insert into Workspace.InternationalOrders Values  (10881, 'Röd Kaviar and other Workspace.Products for personal use', 68.5298);
Insert into Workspace.InternationalOrders Values  (10368, 'Wimmers gute Semmelknödel and other Workspace.Products for personal use', 837.9828);
Insert into Workspace.InternationalOrders Values  (10492, 'Singaporean Hokkien Fried Mee and other Workspace.Products for personal use', 409.3516);
Insert into Workspace.InternationalOrders Values  (11062, 'Perth Pasties and other Workspace.Products for personal use', 232.0877);
Insert into Workspace.InternationalOrders Values  (11043, 'Queso Cabrales and other Workspace.Products for personal use', 95.9418);
Insert into Workspace.InternationalOrders Values  (10763, 'Sir Rodney''s Scones and other Workspace.Products for personal use', 281.4292);
Insert into Workspace.InternationalOrders Values  (11020, 'Ikura and other Workspace.Products for personal use', 339.9080);
Insert into Workspace.InternationalOrders Values  (10738, 'Pavlova and other Workspace.Products for personal use', 23.9169);
Insert into Workspace.InternationalOrders Values  (10633, 'Tarte au sucre and other Workspace.Products for personal use', 2961.8824);
Insert into Workspace.InternationalOrders Values  (10818, 'Mascarpone Fabioli and other Workspace.Products for personal use', 380.5690);
Insert into Workspace.InternationalOrders Values  (10837, 'Zaanse koeken and other Workspace.Products for personal use', 572.9094);
Insert into Workspace.InternationalOrders Values  (10431, 'Zaanse koeken and other Workspace.Products for personal use', 1152.6719);
Insert into Workspace.InternationalOrders Values  (11028, 'Raclette Courdavault and other Workspace.Products for personal use', 986.8297);
Insert into Workspace.InternationalOrders Values  (10265, 'Outback Lager and other Workspace.Products for personal use', 537.2739);
Insert into Workspace.InternationalOrders Values  (10595, 'Steeleye Stout and other Workspace.Products for personal use', 2878.2532);
Insert into Workspace.InternationalOrders Values  (10694, 'Uncle Bob''s Organic Dried Pears and other Workspace.Products for personal use', 2204.3764);
Insert into Workspace.InternationalOrders Values  (10572, 'Rhönbräu Klosterbier and other Workspace.Products for personal use', 715.2916);
Insert into Workspace.InternationalOrders Values  (10267, 'Raclette Courdavault and other Workspace.Products for personal use', 1841.6252);
Insert into Workspace.InternationalOrders Values  (10395, 'Spegesild and other Workspace.Products for personal use', 1065.9588);
Insert into Workspace.InternationalOrders Values  (10448, 'Gumbär Gummibärchen and other Workspace.Products for personal use', 202.5742);
Insert into Workspace.InternationalOrders Values  (10248, 'Singaporean Hokkien Fried Mee and other Workspace.Products for personal use', 201.0209);
Insert into Workspace.InternationalOrders Values  (10490, 'Scottish Longbreads and other Workspace.Products for personal use', 1445.1572);
Insert into Workspace.InternationalOrders Values  (10286, 'Tarte au sucre and other Workspace.Products for personal use', 1377.9066);
Insert into Workspace.InternationalOrders Values  (10408, 'Tourtière and other Workspace.Products for personal use', 741.2187);
Insert into Workspace.InternationalOrders Values  (11001, 'Uncle Bob''s Organic Dried Pears and other Workspace.Products for personal use', 1265.0608);
Insert into Workspace.InternationalOrders Values  (10639, 'Carnarvon Tigers and other Workspace.Products for personal use', 228.4328);
Insert into Workspace.InternationalOrders Values  (10835, 'Raclette Courdavault and other Workspace.Products for personal use', 388.7926);
Insert into Workspace.InternationalOrders Values  (10839, 'Mozzarella di Giovanni and other Workspace.Products for personal use', 420.0879);
Insert into Workspace.InternationalOrders Values  (10959, 'Rhönbräu Klosterbier and other Workspace.Products for personal use', 70.8142);
Insert into Workspace.InternationalOrders Values  (10755, 'Zaanse koeken and other Workspace.Products for personal use', 1186.9368);
Insert into Workspace.InternationalOrders Values  (10734, 'Nord-Ost Matjeshering and other Workspace.Products for personal use', 684.5445);
Insert into Workspace.InternationalOrders Values  (10328, 'Scottish Longbreads and other Workspace.Products for personal use', 533.6190);
Insert into Workspace.InternationalOrders Values  (10496, 'Gorgonzola Telino and other Workspace.Products for personal use', 91.3731);
Insert into Workspace.InternationalOrders Values  (10631, 'Rhönbräu Klosterbier and other Workspace.Products for personal use', 28.3257);
Insert into Workspace.InternationalOrders Values  (10288, 'Tourtière and other Workspace.Products for personal use', 40.6610);
Insert into Workspace.InternationalOrders Values  (10551, 'Steeleye Stout and other Workspace.Products for personal use', 838.8052);
Insert into Workspace.InternationalOrders Values  (10877, 'Pavlova and other Workspace.Products for personal use', 953.0216);
Insert into Workspace.InternationalOrders Values  (10387, 'Rössle Sauerkraut and other Workspace.Products for personal use', 483.5465);
Insert into Workspace.InternationalOrders Values  (10511, 'Uncle Bob''s Organic Dried Pears and other Workspace.Products for personal use', 1370.5967);
Insert into Workspace.InternationalOrders Values  (10801, 'Thüringer Rostbratwurst and other Workspace.Products for personal use', 1843.8181);
Insert into Workspace.InternationalOrders Values  (10345, 'Teatime Chocolate Biscuits and other Workspace.Products for personal use', 1336.2404);
Insert into Workspace.InternationalOrders Values  (10553, 'Steeleye Stout and other Workspace.Products for personal use', 706.4512);
Insert into Workspace.InternationalOrders Values  (10999, 'Original Frankfurter grüne Soße and other Workspace.Products for personal use', 576.1075);
Insert into Workspace.InternationalOrders Values  (10530, 'Sirop d''érable and other Workspace.Products for personal use', 1909.6981);
Insert into Workspace.InternationalOrders Values  (10652, 'Singaporean Hokkien Fried Mee and other Workspace.Products for personal use', 151.5789);
Insert into Workspace.InternationalOrders Values  (10673, 'Singaporean Hokkien Fried Mee and other Workspace.Products for personal use', 188.3885);
Insert into Workspace.InternationalOrders Values  (10515, 'Schoggi Schokolade and other Workspace.Products for personal use', 4837.5212);
Insert into Workspace.InternationalOrders Values  (10793, 'Jack''s New England Clam Chowder and other Workspace.Products for personal use', 87.3070);
Insert into Workspace.InternationalOrders Values  (10410, 'Raclette Courdavault and other Workspace.Products for personal use', 366.4062);
Insert into Workspace.InternationalOrders Values  (10856, 'Singaporean Hokkien Fried Mee and other Workspace.Products for personal use', 301.5313);
Insert into Workspace.InternationalOrders Values  (10795, 'Pavlova and other Workspace.Products for personal use', 1141.8213);
Insert into Workspace.InternationalOrders Values  (10509, 'Rössle Sauerkraut and other Workspace.Products for personal use', 62.4992);
Insert into Workspace.InternationalOrders Values  (10938, 'Konbu and other Workspace.Products for personal use', 1664.1329);
Insert into Workspace.InternationalOrders Values  (10780, 'Outback Lager and other Workspace.Products for personal use', 328.9432);
Insert into Workspace.InternationalOrders Values  (10915, 'Tourtière and other Workspace.Products for personal use', 246.4790);
Insert into Workspace.InternationalOrders Values  (10593, 'Sir Rodney''s Marmalade and other Workspace.Products for personal use', 1138.9659);
Insert into Workspace.InternationalOrders Values  (10406, 'Sir Rodney''s Scones and other Workspace.Products for personal use', 922.0461);
Insert into Workspace.InternationalOrders Values  (10917, 'Nord-Ost Matjeshering and other Workspace.Products for personal use', 167.1625);
Insert into Workspace.InternationalOrders Values  (10978, 'Sir Rodney''s Scones and other Workspace.Products for personal use', 685.6182);
Insert into Workspace.InternationalOrders Values  (11060, 'Original Frankfurter grüne Soße and other Workspace.Products for personal use', 121.5262);
Insert into Workspace.InternationalOrders Values  (11045, 'Manjimup Dried Apples and other Workspace.Products for personal use', 598.2655);
Insert into Workspace.InternationalOrders Values  (10976, 'Rössle Sauerkraut and other Workspace.Products for personal use', 416.6614);
Insert into Workspace.InternationalOrders Values  (10450, 'Tourtière and other Workspace.Products for personal use', 242.7784);
Insert into Workspace.InternationalOrders Values  (10671, 'Tarte au sucre and other Workspace.Products for personal use', 420.3620);
Insert into Workspace.InternationalOrders Values  (10467, 'NuNuCa Nuß-Nougat-Creme and other Workspace.Products for personal use', 107.4548);
Insert into Workspace.InternationalOrders Values  (10774, 'Louisiana Hot Spiced Okra and other Workspace.Products for personal use', 399.7574);
Insert into Workspace.InternationalOrders Values  (10488, 'Röd Kaviar and other Workspace.Products for personal use', 712.7103);
Insert into Workspace.InternationalOrders Values  (10963, 'Camembert Pierrot and other Workspace.Products for personal use', 31.0669);
Insert into Workspace.InternationalOrders Values  (10568, 'Ikura and other Workspace.Products for personal use', 70.8142);
Insert into Workspace.InternationalOrders Values  (10919, 'Pavlova and other Workspace.Products for personal use', 512.9687);
Insert into Workspace.InternationalOrders Values  (10997, 'Spegesild and other Workspace.Products for personal use', 904.5938);
Insert into Workspace.InternationalOrders Values  (10732, 'Lakkalikööri and other Workspace.Products for personal use', 164.4716);
Insert into Workspace.InternationalOrders Values  (11039, 'Steeleye Stout and other Workspace.Products for personal use', 1411.7146);
Insert into Workspace.InternationalOrders Values  (10957, 'Wimmers gute Semmelknödel and other Workspace.Products for personal use', 805.3170);
Insert into Workspace.InternationalOrders Values  (10412, 'Tofu and other Workspace.Products for personal use', 169.9540);
Insert into Workspace.InternationalOrders Values  (10261, 'Steeleye Stout and other Workspace.Products for personal use', 204.6758);
Insert into Workspace.InternationalOrders Values  (10715, 'Ikura and other Workspace.Products for personal use', 592.0978);
Insert into Workspace.InternationalOrders Values  (10650, 'Tourtière and other Workspace.Products for personal use', 831.5867);
Insert into Workspace.InternationalOrders Values  (10772, 'Thüringer Rostbratwurst and other Workspace.Products for personal use', 1646.1872);
Insert into Workspace.InternationalOrders Values  (10692, 'Vegie-spread and other Workspace.Products for personal use', 401.1280);
Insert into Workspace.InternationalOrders Values  (10284, 'Schoggi Schokolade and other Workspace.Products for personal use', 663.3688);
Insert into Workspace.InternationalOrders Values  (10677, 'Gumbär Gummibärchen and other Workspace.Products for personal use', 437.1747);
Insert into Workspace.InternationalOrders Values  (10730, 'Pavlova and other Workspace.Products for personal use', 232.8872);
Insert into Workspace.InternationalOrders Values  (10898, 'Konbu and other Workspace.Products for personal use', 13.7060);
Insert into Workspace.InternationalOrders Values  (10833, 'Uncle Bob''s Organic Dried Pears and other Workspace.Products for personal use', 460.3834);
Insert into Workspace.InternationalOrders Values  (11037, 'Outback Lager and other Workspace.Products for personal use', 27.4119);
Insert into Workspace.InternationalOrders Values  (10854, 'Konbu and other Workspace.Products for personal use', 1594.4609);
Insert into Workspace.InternationalOrders Values  (10753, 'Rogede sild and other Workspace.Products for personal use', 40.2042);
Insert into Workspace.InternationalOrders Values  (10513, 'Sirop d''érable and other Workspace.Products for personal use', 1109.0412);
Insert into Workspace.InternationalOrders Values  (11056, 'Uncle Bob''s Organic Dried Pears and other Workspace.Products for personal use', 1708.6773);
Insert into Workspace.InternationalOrders Values  (10326, 'Rhönbräu Klosterbier and other Workspace.Products for personal use', 448.6420);
Insert into Workspace.InternationalOrders Values  (11016, 'Inlagd Sill and other Workspace.Products for personal use', 224.5494);
Insert into Workspace.InternationalOrders Values  (10629, 'Wimmers gute Semmelknödel and other Workspace.Products for personal use', 1267.8248);
Insert into Workspace.InternationalOrders Values  (10364, 'Gudbrandsdalsost and other Workspace.Products for personal use', 434.0223);
Insert into Workspace.InternationalOrders Values  (10303, 'Scottish Longbreads and other Workspace.Products for personal use', 567.4270);
Insert into Workspace.InternationalOrders Values  (10309, 'Singaporean Hokkien Fried Mee and other Workspace.Products for personal use', 804.9972);
Insert into Workspace.InternationalOrders Values  (10913, 'Geitost and other Workspace.Products for personal use', 438.0199);
Insert into Workspace.InternationalOrders Values  (10591, 'Uncle Bob''s Organic Dried Pears and other Workspace.Products for personal use', 371.2033);
Insert into Workspace.InternationalOrders Values  (10669, 'Inlagd Sill and other Workspace.Products for personal use', 260.4134);
Insert into Workspace.InternationalOrders Values  (10282, 'Ravioli Angelo and other Workspace.Products for personal use', 70.9969);
Insert into Workspace.InternationalOrders Values  (10486, 'Queso Cabrales and other Workspace.Products for personal use', 581.1330);
Insert into Workspace.InternationalOrders Values  (10425, 'Pâté chinois and other Workspace.Products for personal use', 219.2955);
Insert into Workspace.InternationalOrders Values  (10778, 'Jack''s New England Clam Chowder and other Workspace.Products for personal use', 44.0875);
Insert into Workspace.InternationalOrders Values  (10505, 'Tarte au sucre and other Workspace.Products for personal use', 67.5704);
Insert into Workspace.InternationalOrders Values  (10570, 'Queso Cabrales and other Workspace.Products for personal use', 1185.5662);
Insert into Workspace.InternationalOrders Values  (10831, 'Teatime Chocolate Biscuits and other Workspace.Products for personal use', 1226.4100);
Insert into Workspace.InternationalOrders Values  (10547, 'Mascarpone Fabioli and other Workspace.Products for personal use', 871.6995);
Insert into Workspace.InternationalOrders Values  (10751, 'Valkoinen suklaa and other Workspace.Products for personal use', 777.3385);
Insert into Workspace.InternationalOrders Values  (10648, 'Gustaf''s Knäckebröd and other Workspace.Products for personal use', 174.7511);
Insert into Workspace.InternationalOrders Values  (10614, 'Sir Rodney''s Scones and other Workspace.Products for personal use', 211.9856);
Insert into Workspace.InternationalOrders Values  (10566, 'Queso Cabrales and other Workspace.Products for personal use', 932.0058);
Insert into Workspace.InternationalOrders Values  (10427, 'Tofu and other Workspace.Products for personal use', 297.4195);
Insert into Workspace.InternationalOrders Values  (10423, 'Raclette Courdavault and other Workspace.Products for personal use', 466.0029);
Insert into Workspace.InternationalOrders Values  (10812, 'Original Frankfurter grüne Soße and other Workspace.Products for personal use', 846.1151);
Insert into Workspace.InternationalOrders Values  (10404, 'Singaporean Hokkien Fried Mee and other Workspace.Products for personal use', 765.2498);
Insert into Workspace.InternationalOrders Values  (10709, 'Northwoods Cranberry Sauce and other Workspace.Products for personal use', 1564.3077);
Insert into Workspace.InternationalOrders Values  (10879, 'Louisiana Fiery Hot Pepper Sauce and other Workspace.Products for personal use', 279.2819);
Insert into Workspace.InternationalOrders Values  (10892, 'Raclette Courdavault and other Workspace.Products for personal use', 1005.1043);
Insert into Workspace.InternationalOrders Values  (10610, 'Inlagd Sill and other Workspace.Products for personal use', 182.2894);
Insert into Workspace.InternationalOrders Values  (10688, 'Sasquatch Ale and other Workspace.Products for personal use', 1594.4609);
Insert into Workspace.InternationalOrders Values  (10873, 'Sir Rodney''s Scones and other Workspace.Products for personal use', 153.8723);
Insert into Workspace.InternationalOrders Values  (10526, 'Konbu and other Workspace.Products for personal use', 614.0273);
Insert into Workspace.InternationalOrders Values  (10301, 'Gnocchi di nonna Alice and other Workspace.Products for personal use', 344.9335);
Insert into Workspace.InternationalOrders Values  (10736, 'Rhönbräu Klosterbier and other Workspace.Products for personal use', 455.4950);
Insert into Workspace.InternationalOrders Values  (10484, 'Sir Rodney''s Scones and other Workspace.Products for personal use', 176.4415);
Insert into Workspace.InternationalOrders Values  (10875, 'Zaanse koeken and other Workspace.Products for personal use', 333.2834);
Insert into Workspace.InternationalOrders Values  (10728, 'Pâté chinois and other Workspace.Products for personal use', 592.4404);
Insert into Workspace.InternationalOrders Values  (10587, 'Steeleye Stout and other Workspace.Products for personal use', 368.8641);
Insert into Workspace.InternationalOrders Values  (10995, 'Manjimup Dried Apples and other Workspace.Products for personal use', 546.4112);
Insert into Workspace.InternationalOrders Values  (10770, 'Queso Cabrales and other Workspace.Products for personal use', 143.9127);
Insert into Workspace.InternationalOrders Values  (10532, 'Nord-Ost Matjeshering and other Workspace.Products for personal use', 363.8249);
Insert into Workspace.InternationalOrders Values  (11014, 'Jack''s New England Clam Chowder and other Workspace.Products for personal use', 123.4451);
Insert into Workspace.InternationalOrders Values  (10343, 'Wimmers gute Semmelknödel and other Workspace.Products for personal use', 724.5888);
Insert into Workspace.InternationalOrders Values  (10993, 'Thüringer Rostbratwurst and other Workspace.Products for personal use', 2982.0759);
Insert into Workspace.InternationalOrders Values  (10444, 'Steeleye Stout and other Workspace.Products for personal use', 471.3482);
Insert into Workspace.InternationalOrders Values  (10791, 'Thüringer Rostbratwurst and other Workspace.Products for personal use', 879.9505);
Insert into Workspace.InternationalOrders Values  (10585, 'Zaanse koeken and other Workspace.Products for personal use', 65.1033);
Insert into Workspace.InternationalOrders Values  (10797, 'Queso Cabrales and other Workspace.Products for personal use', 191.8835);
Insert into Workspace.InternationalOrders Values  (10606, 'Tarte au sucre and other Workspace.Products for personal use', 645.5511);
Insert into Workspace.InternationalOrders Values  (10608, 'Gnocchi di nonna Alice and other Workspace.Products for personal use', 486.1050);
Insert into Workspace.InternationalOrders Values  (10381, 'Longlife Tofu and other Workspace.Products for personal use', 51.1689);
Insert into Workspace.InternationalOrders Values  (10749, 'Raclette Courdavault and other Workspace.Products for personal use', 493.4148);
Insert into Workspace.InternationalOrders Values  (11035, 'Tourtière and other Workspace.Products for personal use', 801.5707);
Insert into Workspace.InternationalOrders Values  (10850, 'Outback Lager and other Workspace.Products for personal use', 338.0805);
Insert into Workspace.InternationalOrders Values  (10980, 'Rhönbräu Klosterbier and other Workspace.Products for personal use', 141.6283);
Insert into Workspace.InternationalOrders Values  (11075, 'Spegesild and other Workspace.Products for personal use', 267.7232);
Insert into Workspace.InternationalOrders Values  (10465, 'Valkoinen suklaa and other Workspace.Products for personal use', 1242.2175);
Insert into Workspace.InternationalOrders Values  (10421, 'Teatime Chocolate Biscuits and other Workspace.Products for personal use', 581.6813);
Insert into Workspace.InternationalOrders Values  (10341, 'Raclette Courdavault and other Workspace.Products for personal use', 188.2286);
Insert into Workspace.InternationalOrders Values  (10789, 'Vegie-spread and other Workspace.Products for personal use', 1684.4634);
Insert into Workspace.InternationalOrders Values  (10972, 'Geitost and other Workspace.Products for personal use', 114.9017);
Insert into Workspace.InternationalOrders Values  (10776, 'Singaporean Hokkien Fried Mee and other Workspace.Products for personal use', 3190.9776);
Insert into Workspace.InternationalOrders Values  (10402, 'Vegie-spread and other Workspace.Products for personal use', 1239.7048);
Insert into Workspace.InternationalOrders Values  (10934, 'Grandma''s Boysenberry Spread and other Workspace.Products for personal use', 228.4328);
Insert into Workspace.InternationalOrders Values  (10667, 'Gudbrandsdalsost and other Workspace.Products for personal use', 877.6388);
Insert into Workspace.InternationalOrders Values  (11054, 'Laughing Lumberjack Lager and other Workspace.Products for personal use', 139.3440);
Insert into Workspace.InternationalOrders Values  (10829, 'Northwoods Cranberry Sauce and other Workspace.Products for personal use', 805.9109);
Insert into Workspace.InternationalOrders Values  (11041, 'Vegie-spread and other Workspace.Products for personal use', 862.1053);
Insert into Workspace.InternationalOrders Values  (10871, 'Pavlova and other Workspace.Products for personal use', 951.8337);
Insert into Workspace.InternationalOrders Values  (10322, 'Filo Mix and other Workspace.Products for personal use', 51.1689);
Insert into Workspace.InternationalOrders Values  (10932, 'Tarte au sucre and other Workspace.Products for personal use', 879.6947);
Insert into Workspace.InternationalOrders Values  (10503, 'Tofu and other Workspace.Products for personal use', 935.8891);
Insert into Workspace.InternationalOrders Values  (10400, 'Thüringer Rostbratwurst and other Workspace.Products for personal use', 1399.3793);
Insert into Workspace.InternationalOrders Values  (10429, 'Vegie-spread and other Workspace.Products for personal use', 798.8295);
Insert into Workspace.InternationalOrders Values  (10320, 'Flotemysost and other Workspace.Products for personal use', 235.7426);
Insert into Workspace.InternationalOrders Values  (10362, 'Tourtière and other Workspace.Products for personal use', 707.9589);
Insert into Workspace.InternationalOrders Values  (10524, 'Tourtière and other Workspace.Products for personal use', 1458.6119);
Insert into Workspace.InternationalOrders Values  (10278, 'Vegie-spread and other Workspace.Products for personal use', 680.1815);
Insert into Workspace.InternationalOrders Values  (10366, 'Original Frankfurter grüne Soße and other Workspace.Products for personal use', 62.1337);
Insert into Workspace.InternationalOrders Values  (10707, 'Ravioli Angelo and other Workspace.Products for personal use', 778.4989);
Insert into Workspace.InternationalOrders Values  (10953, 'Sir Rodney''s Marmalade and other Workspace.Products for personal use', 2135.8466);
Insert into Workspace.InternationalOrders Values  (10299, 'Teatime Chocolate Biscuits and other Workspace.Products for personal use', 159.6745);
Insert into Workspace.InternationalOrders Values  (10747, 'Vegie-spread and other Workspace.Products for personal use', 873.9153);
Insert into Workspace.InternationalOrders Values  (10896, 'Rogede sild and other Workspace.Products for personal use', 342.8776);
Insert into Workspace.InternationalOrders Values  (10768, 'Gustaf''s Knäckebröd and other Workspace.Products for personal use', 674.7905);
Insert into Workspace.InternationalOrders Values  (10646, 'Original Frankfurter grüne Soße and other Workspace.Products for personal use', 880.8368);
Insert into Workspace.InternationalOrders Values  (10890, 'Sasquatch Ale and other Workspace.Products for personal use', 392.9501);
Insert into Workspace.InternationalOrders Values  (10604, 'Lakkalikööri and other Workspace.Products for personal use', 117.1860);
Insert into Workspace.InternationalOrders Values  (10549, 'Rogede sild and other Workspace.Products for personal use', 1910.3834);
Insert into Workspace.InternationalOrders Values  (11033, 'Perth Pasties and other Workspace.Products for personal use', 1641.0612);
Insert into Workspace.InternationalOrders Values  (10911, 'Laughing Lumberjack Lager and other Workspace.Products for personal use', 391.9907);
Insert into Workspace.InternationalOrders Values  (10339, 'Tarte au sucre and other Products for personal use', 1582.2169);
Insert into Workspace.InternationalOrders Values  (10869, 'Tunnbröd and other Products for personal use', 744.6909);
Insert into Workspace.InternationalOrders Values  (10814, 'Sirop d''érable and other Products for personal use', 945.7117);
Insert into Workspace.InternationalOrders Values  (10686, 'Gumbär Gummibärchen and other Products for personal use', 748.5514);
Insert into Workspace.InternationalOrders Values  (10360, 'Tourtière and other Products for personal use', 3376.3280);
Insert into Workspace.InternationalOrders Values  (10263, 'Pavlova and other Products for personal use', 1126.0823);
Insert into Workspace.InternationalOrders Values  (10543, 'Tunnbröd and other Products for personal use', 808.6521);
Insert into Workspace.InternationalOrders Values  (10625, 'Tofu and other Products for personal use', 219.1813);
Insert into Workspace.InternationalOrders Values  (11058, 'Sirop d''érable and other Products for personal use', 391.9907);
Insert into Workspace.InternationalOrders Values  (10951, 'Rhönbräu Klosterbier and other Products for personal use', 220.6204);
Insert into Workspace.InternationalOrders Values  (10446, 'Teatime Chocolate Biscuits and other Products for personal use', 124.9984);
Insert into Workspace.InternationalOrders Values  (11073, 'Queso Cabrales and other Products for personal use', 137.0597);
Insert into Workspace.InternationalOrders Values  (10507, 'Ipoh Coffee and other Products for personal use', 402.6128);
Insert into Workspace.InternationalOrders Values  (10690, 'Original Frankfurter grüne Soße and other Products for personal use', 525.3954);
Insert into Workspace.InternationalOrders Values  (10955, 'Rhönbräu Klosterbier and other Products for personal use', 42.4885);
Insert into Workspace.InternationalOrders Values  (10383, 'Valkoinen suklaa and other Products for personal use', 410.7222);
Insert into Workspace.InternationalOrders Values  (10280, 'Rhönbräu Klosterbier and other Products for personal use', 280.1500);
Insert into Workspace.InternationalOrders Values  (10810, 'Outback Lager and other Products for personal use', 85.4339);
Insert into Workspace.InternationalOrders Values  (10463, 'Teatime Chocolate Biscuits and other Products for personal use', 325.8822);
Insert into Workspace.InternationalOrders Values  (10259, 'Sir Rodney''s Scones and other Products for personal use', 46.0521);
Insert into Workspace.InternationalOrders Values  (10442, 'Tourtière and other Products for personal use', 818.7031);
Insert into Workspace.InternationalOrders Values  (11012, 'Teatime Chocolate Biscuits and other Products for personal use', 1358.7182);


select * from Workspace.InternationalOrders;
-- ------------------------------------------------------------------------
